// seed.js — default exercise program (extracted from user's "פולבודי - ששי דניאל" plan)
export const SEED_EXERCISES = [
  { name: 'לחיצת חזה', category: 'חזה', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: "במשקולות חופשיות / בסמית' / במכונה / במוט",
    images: ['images/p2_1.png', 'images/p2_2.png'] },
  { name: 'פרפר חזה', category: 'חזה', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: 'בקייבל קרוס / במשקולות יד בשכיבה / במכונה',
    images: ['images/p2_3.png', 'images/p2_4.png'] },

  { name: 'משיכה לפנים בפולי עליון (אחיזה רחבה)', category: 'גב', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: 'במכונה / מתח',
    images: ['images/p3_1.png'] },
  { name: 'חתירה צרה לבטן', category: 'גב', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: 'בפולי תחתון / במשקולת יד בהטיית גב על ספסל / במכונה',
    images: ['images/p3_2.png', 'images/p3_3.png'] },

  { name: 'לחיצת רגליים', category: 'רגליים', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: "במכונה / האק / סקוואט בסמית' משין / סקוואט חופשי",
    images: ['images/p4_1.png'] },
  { name: 'פשיטת ברכיים', category: 'רגליים', defaultSets: 3, defaultReps: '15-20', restSeconds: 90,
    notes: '(מכונה)',
    images: ['images/p4_2.png'] },
  { name: 'כפיפת ברכיים', category: 'רגליים', defaultSets: 3, defaultReps: '15-20', restSeconds: 90,
    notes: '(מכונה)',
    images: ['images/p4_3.png'] },

  { name: 'הרחקה לצדדים עם משקולות יד', category: 'כתפיים', defaultSets: 3, defaultReps: '15-20', restSeconds: 90,
    notes: 'בישיבה / במכונה',
    images: ['images/p5_1.png', 'images/p5_2.png'] },
  { name: 'הרחקה אופקית (פרפר הפוך)', category: 'כתפיים', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: 'במשקולות יד עם השענות על ספסל / בהטיית גב בעמידה / במכונה',
    images: ['images/p5_3.png', 'images/p5_4.png'] },

  { name: 'פשיטת מרפקים בפולי עליון', category: 'יד אחורית (טריצפס)', defaultSets: 3, defaultReps: '12-15', restSeconds: 90,
    notes: 'כנגד מוט/חבל, או פשיטת מרפק מאחורי העורף עם משקולת',
    images: ['images/p6_1.png', 'images/p6_2.png'] },

  { name: 'כפיפת מרפקים בישיבה', category: 'יד קדמית (ביצפס)', defaultSets: 2, defaultReps: '12-15', restSeconds: 90,
    notes: "כנגד משקולות יד / בכיסא כומר / במכונה",
    images: ['images/p7_1.png', 'images/p7_2.png'] },
  { name: 'פטישים (Hammer Curls)', category: 'יד קדמית (ביצפס)', defaultSets: 1, defaultReps: 'עד כשל', restSeconds: 60,
    notes: 'סט אחד לכל יד עד כשל',
    images: [] },
  { name: 'כפיפה ופשיטה של שורש כף היד (Wrist Curl)', category: 'יד קדמית (ביצפס)', defaultSets: 1, defaultReps: 'עד כשל', restSeconds: 60,
    notes: 'סט אחד לכל תנועה לכל יד עד כשל',
    images: ['images/p7_3.png'] },

  { name: 'כפיפות בטן / רולאפ', category: 'בטן / גב תחתון', defaultSets: 3, defaultReps: '15-25', restSeconds: 60,
    notes: '(Crunches) על הרצפה או עם גלגלת',
    images: ['images/p8_1.png'] },
  { name: 'זוקפי גב — פשיטת גב', category: 'בטן / גב תחתון', defaultSets: 3, defaultReps: '15-25', restSeconds: 60,
    notes: 'על הרצפה / בכסא רומי / מכונת היפראקסטנשן',
    images: ['images/p8_2.png', 'images/p8_3.png'] },
];
